In [1]:
import numpy as np
from help_functions import *
import os

# Extend separation of c

In [3]:
arr_vertices, faces = read_off("data/util/c_template.off")

In [4]:
arr_vertices

array([[ 0. ,  0. ,  0. ],
       [ 7. ,  0. ,  0. ],
       [ 7. ,  3. ,  0. ],
       [ 5. ,  3. ,  0. ],
       [ 5. ,  2. ,  0. ],
       [ 2. ,  2. ,  0. ],
       [ 2. ,  5. ,  0. ],
       [ 5. ,  5. ,  0. ],
       [ 5. ,  4. ,  0. ],
       [ 7. ,  4. ,  0. ],
       [ 7. ,  7. ,  0. ],
       [ 0. ,  7. ,  0. ],
       [ 0. ,  0. , -3.5],
       [ 7. ,  0. , -3.5],
       [ 7. ,  3. , -3.5],
       [ 5. ,  3. , -3.5],
       [ 5. ,  2. , -3.5],
       [ 2. ,  2. , -3.5],
       [ 2. ,  5. , -3.5],
       [ 5. ,  5. , -3.5],
       [ 5. ,  4. , -3.5],
       [ 7. ,  4. , -3.5],
       [ 7. ,  7. , -3.5],
       [ 0. ,  7. , -3.5]])

In [25]:
mid_coord = 3.5 #* 2
separation = 0.8849 #* 2

new_vertices = arr_vertices.copy()
#new_vertices = new_vertices * 2

top_indices = [8, 9, 20, 21]
bottom_indices = [2, 3, 14, 15]

top_values = np.array([mid_coord + separation/2] * len(top_indices))
bottom_values = np.array([mid_coord - separation/2] * len(bottom_indices))

new_vertices[top_indices, 1] = top_values
new_vertices[bottom_indices, 1] = bottom_values
#display(new_vertices)

In [26]:
write_vertex(new_vertices, faces, f"data/util/c_sep_{separation:.4f}.off")

# Tests

In [47]:
RL = 2
factor = 0.35
octant_side = 7 / 2 ** (RL + 1)
long_diag = np.sqrt(3) * octant_side
(1 - factor) * long_diag

np.float64(0.9851038968047989)

In [30]:
a = 0.885

In [3]:
os.getcwd()

'/home/joacaldo/memoria'

In [11]:
import os

filename = "~/memoria/data/util/test"
os.path.exists(filename), filename.endswith(".off")

(False, False)

In [20]:
import argparse
# Set up argument parsing
parser = argparse.ArgumentParser(description="Run mesher_roi with specified parameters.")


In [24]:
a = {'tamara': False, 'input': 'c_norm', 'surface': 3}

a['tamara']

False

In [26]:
from commands import *

params = [{'tamara': True, 'input': 'c_norm', 'surface': 2},
          {'tamara': True, 'input': 'c_norm', 'surface': 3},
          {'tamara': True, 'input': 'c_norm', 'surface': 4}]

for p in params:
	print(p)
	run_mesher(p)

{'tamara': True, 'input': 'c_norm', 'surface': 2}
/home/joacaldo/memoria/mesher-reupload/mesher/build/mesher_roi -o /home/joacaldo/memoria/data/util/c_norm.off -u /home/joacaldo/memoria/data/out_tamara/c_norm_s2 -s 2
Command executed successfully!
Output:   All done in 11 ms

File saved to /home/joacaldo/memoria/data/out_tamara/c_norm_s2.vtk
{'tamara': True, 'input': 'c_norm', 'surface': 3}
/home/joacaldo/memoria/mesher-reupload/mesher/build/mesher_roi -o /home/joacaldo/memoria/data/util/c_norm.off -u /home/joacaldo/memoria/data/out_tamara/c_norm_s3 -s 3
Command executed successfully!
Output:   All done in 30 ms

File saved to /home/joacaldo/memoria/data/out_tamara/c_norm_s3.vtk
{'tamara': True, 'input': 'c_norm', 'surface': 4}
/home/joacaldo/memoria/mesher-reupload/mesher/build/mesher_roi -o /home/joacaldo/memoria/data/util/c_norm.off -u /home/joacaldo/memoria/data/out_tamara/c_norm_s4 -s 4
Command executed successfully!
Output:   All done in 145 ms

File saved to /home/joacaldo/memor

In [5]:
import os

MESHER = "/home/joacaldo/memoria/mesher/build/mesher_roi"

os.path.dirname(os.path.dirname(MESHER))

'/home/joacaldo/memoria/mesher'

In [2]:
(8.8025 + -1.8025)/2, (0.0175 + -3.5175) /2

(3.5, -1.75)

In [14]:
import numpy as np

points = []

with open("points.txt", "r") as f:
	for line in f:
		points.append([float(x) for x in line.split()])

points = np.array(points)
points

array([[ -8.08  , -40.4   , -19.2748],
       [  8.08  , -40.4   , -19.2748],
       [ -8.08  , -24.24  , -19.2748],
       ...,
       [  0.    ,   0.    ,  47.3852],
       [  2.02  ,   0.    ,  49.4052],
       [  2.02  ,   0.    ,  47.3852]])

In [15]:
import numpy as np

p1 = []
p2 = []

with open("candidate_split_points_3way-activated.txt", "r") as f:
	for line in f:
		p1.append(int(line))
p1 = np.array(p1)

with open("candidate_split_points_3way-deactivated.txt", "r") as f:
	for line in f:
		p2.append(int(line))
p2 = np.array(p2)

print(p1.shape, p2.shape)

# Get the intersection
np.intersect1d(p1, p2).shape

# p1 without the elements in p2
indices = p1[np.isin(p1, p2, invert=True)]
indices.shape

(651,) (14,)


(637,)

In [25]:
splitted_points = points[indices]
splitted_points.shape

(637, 3)

In [59]:
# Get the splitted points max and min x
max_x = np.max(splitted_points[:, 0])
min_x = np.min(splitted_points[:, 0])
print(max_x, min_x)

# Get the splitted points max and min y
max_y = np.max(splitted_points[:, 1])
min_y = np.min(splitted_points[:, 1])
print(max_y, min_y)

# Get the splitted points max and min z
max_z = np.max(splitted_points[:, 2])
min_z = np.min(splitted_points[:, 2])
print(max_z, min_z)

8.08 -8.08
34.34 -34.34
55.4652 -13.2148


In [60]:
(max_y + min_y)/2

np.float64(0.0)

In [70]:
# Get the splitted points with z > C
condition = (splitted_points[:, 2] > max_z - 2.03 * 0.1) & (splitted_points[:, 1] == 0.0)

splitted_points_w_condition = splitted_points[condition]
splitted_points_w_condition

array([[-4.04  ,  0.    , 55.4652],
       [-6.06  ,  0.    , 55.4652],
       [ 0.    ,  0.    , 55.4652],
       [-2.02  ,  0.    , 55.4652]])

In [71]:
# Get the indices of the splitted points with z > C
indices_w_condition = indices[condition]
indices_w_condition

array([5136, 5140, 5144, 5147])

In [72]:
points[5144]

array([ 0.    ,  0.    , 55.4652])

# Mesh repairing

In [2]:
import numpy as np

# Read .off file
with open('data/inputs/guide.off') as f:
	lines = f.readlines()
	n_vertices, n_faces, _ = map(int, lines[1].split())
	print(n_vertices, n_faces)

	vertices_count = 0
	vertices = []

	faces_count = 0
	faces = []

	edges = set()

	for line in lines[2:]: # [2 + 1:2+n_vertices + 1]
		line = line.strip()
		if line == "":
			continue
		if vertices_count < n_vertices:
			vertices.append(list(map(float, line.split())))
			vertices_count += 1
		elif faces_count < n_faces:
			#faces.append(list(map(int, line.split()[1:4])))
			faces_count += 1

			face_data = list(map(int, line.strip().split()[:4]))
			vertex_count = face_data[0]  # First number is the number of vertices in the face
			face_vertices = face_data[1:]

			faces.append(face_vertices)
			
			# Loop through pairs of vertices to create edges
			for i in range(vertex_count):
				v1 = face_vertices[i]
				v2 = face_vertices[(i + 1) % vertex_count]  # Wrap around to form a closed loop
				edge = tuple(sorted((v1, v2)))  # Sort to avoid directional duplicates
				edges.add(edge)
	vertices = np.array(vertices)
	faces = np.array(faces)
	print(vertices.shape)
	print(faces.shape)
	print(len(edges))

1756 3524
(1756, 3)
(3524, 3)
5286


In [22]:
from collections import defaultdict

with open('data/inputs/guide.off', 'r') as f:
	# Read the file header
	header = f.readline().strip()
	if header != 'OFF':
		raise ValueError("Not a valid OFF file")
	
	# Read the counts of vertices, faces, and edges (skip edge count here)
	n_vertices, n_faces, _ = map(int, f.readline().strip().split())

	f.readline()  # Skip space after counts

	# Read vertices
	vertices = []
	for _ in range(n_vertices):
		vertex = tuple(map(float, f.readline().strip().split()))
		vertices.append(vertex)

	f.readline()  # Skip space after vertices
	
	# Read faces and collect edges and their associated faces
	faces = []
	edge_to_faces = defaultdict(list)
	
	for face_index in range(n_faces):
		face_data = list(map(int, f.readline().strip().split()[:4]))
		vertex_count = face_data[0]  # First number is the number of vertices in the face
		face_vertices = face_data[1:]
		faces.append(face_vertices)
		
		# Loop through pairs of vertices to create edges
		for i in range(vertex_count):
			v1 = face_vertices[i]
			v2 = face_vertices[(i + 1) % vertex_count]  # Wrap around to form a closed loop
			edge = tuple(sorted((v1, v2)))  # Sort to avoid directional duplicates
			edge_to_faces[edge].append(face_index)

vertices = np.array(vertices)
faces = np.array(faces)
print(vertices.shape, faces.shape)
	
# Convert edge_to_faces defaultdict to a regular dictionary for output
edge_to_faces = dict(edge_to_faces)

(1756, 3) (3524, 3)


In [23]:
f1, f2 = edge_to_faces[(68, 69)]
f1, f2, faces[f1], faces[f2]

(0, 1495, array([69, 68, 70]), array([  68,   69, 1109]))

In [39]:
a = np.array([68, 70, 69])
b = np.array([68, 1109, 69])

def getContiguousPair(a, v1, v2):
	for i in range(len(a) - 1):
		if (a[i] == v1 and a[i + 1] == v2) or (a[i] == v2 and a[i + 1] == v1):
			return int(a[i]), int(a[i + 1])
	return False

def congruent_array(a1, a2):
	intersect = np.intersect1d(a1, a2)
	v1, v2 = intersect
	# print(v1, v2)

	ad1 = np.concat([a1, a1])
	ad2 = np.concat([a2, a2])
	# print(ad1, ad2)

	p1 = getContiguousPair(ad1, v1, v2)
	p2 = getContiguousPair(ad2, v1, v2)
	assert p1 and p2, "No contiguous pair found"

	# print(p1, p2)
	condition = (p1[0] == p2[1]) and (p1[1] == p2[0])
	# print(condition)
	return condition

congruent_array(a, b)


False

## Hole detection

In [30]:
for edge, faces_indices in edge_to_faces.items():
	if len(faces_indices) != 2:
		print(edge, faces_indices)

## Congruency

In [31]:
for edge, faces_indices in edge_to_faces.items():
	v1, v2 = edge
	f_idx1, f_idx2 = faces_indices

	f1, f2 = faces[f_idx1], faces[f_idx2]

	result = congruent_array(f1, f2)
	
	if not result:
		print(v1, v2, f_idx1, f_idx2, f1, f2)

In [121]:
np.array(np.True_, np.False_)

array(True)

In [ ]:
0, 1
1, 2
2, 0

In [85]:
i = 2
j = (i + 1) % 3
print(i, j)


2 0
