In [2]:
import numpy as np
from help_functions import *

# Extend separation of c

In [4]:
arr_vertices, faces = read_off("data/util/c_template.off")

In [42]:
arr_vertices

array([[ 0. ,  0. ,  0. ],
       [ 7. ,  0. ,  0. ],
       [ 7. ,  3. ,  0. ],
       [ 5. ,  3. ,  0. ],
       [ 5. ,  2. ,  0. ],
       [ 2. ,  2. ,  0. ],
       [ 2. ,  5. ,  0. ],
       [ 5. ,  5. ,  0. ],
       [ 5. ,  4. ,  0. ],
       [ 7. ,  4. ,  0. ],
       [ 7. ,  7. ,  0. ],
       [ 0. ,  7. ,  0. ],
       [ 0. ,  0. , -3.5],
       [ 7. ,  0. , -3.5],
       [ 7. ,  3. , -3.5],
       [ 5. ,  3. , -3.5],
       [ 5. ,  2. , -3.5],
       [ 2. ,  2. , -3.5],
       [ 2. ,  5. , -3.5],
       [ 5. ,  5. , -3.5],
       [ 5. ,  4. , -3.5],
       [ 7. ,  4. , -3.5],
       [ 7. ,  7. , -3.5],
       [ 0. ,  7. , -3.5]])

In [43]:
arr_vertices * 2

array([[ 0.,  0.,  0.],
       [14.,  0.,  0.],
       [14.,  6.,  0.],
       [10.,  6.,  0.],
       [10.,  4.,  0.],
       [ 4.,  4.,  0.],
       [ 4., 10.,  0.],
       [10., 10.,  0.],
       [10.,  8.,  0.],
       [14.,  8.,  0.],
       [14., 14.,  0.],
       [ 0., 14.,  0.],
       [ 0.,  0., -7.],
       [14.,  0., -7.],
       [14.,  6., -7.],
       [10.,  6., -7.],
       [10.,  4., -7.],
       [ 4.,  4., -7.],
       [ 4., 10., -7.],
       [10., 10., -7.],
       [10.,  8., -7.],
       [14.,  8., -7.],
       [14., 14., -7.],
       [ 0., 14., -7.]])

In [60]:
mid_coord = 3.5 #* 2
separation = 0.849 #* 2

new_vertices = arr_vertices.copy()
#new_vertices = new_vertices * 2

top_indices = [8, 9, 20, 21]
bottom_indices = [2, 3, 14, 15]

top_values = np.array([mid_coord + separation/2] * len(top_indices))
bottom_values = np.array([mid_coord - separation/2] * len(bottom_indices))

new_vertices[top_indices, 1] = top_values
new_vertices[bottom_indices, 1] = bottom_values
display(new_vertices)

array([[ 0.    ,  0.    ,  0.    ],
       [ 7.    ,  0.    ,  0.    ],
       [ 7.    ,  3.0755,  0.    ],
       [ 5.    ,  3.0755,  0.    ],
       [ 5.    ,  2.    ,  0.    ],
       [ 2.    ,  2.    ,  0.    ],
       [ 2.    ,  5.    ,  0.    ],
       [ 5.    ,  5.    ,  0.    ],
       [ 5.    ,  3.9245,  0.    ],
       [ 7.    ,  3.9245,  0.    ],
       [ 7.    ,  7.    ,  0.    ],
       [ 0.    ,  7.    ,  0.    ],
       [ 0.    ,  0.    , -3.5   ],
       [ 7.    ,  0.    , -3.5   ],
       [ 7.    ,  3.0755, -3.5   ],
       [ 5.    ,  3.0755, -3.5   ],
       [ 5.    ,  2.    , -3.5   ],
       [ 2.    ,  2.    , -3.5   ],
       [ 2.    ,  5.    , -3.5   ],
       [ 5.    ,  5.    , -3.5   ],
       [ 5.    ,  3.9245, -3.5   ],
       [ 7.    ,  3.9245, -3.5   ],
       [ 7.    ,  7.    , -3.5   ],
       [ 0.    ,  7.    , -3.5   ]])

In [48]:
write_vertex(new_vertices, faces, f"data/util/c_sep_{separation:.4f}_doubled.off")

In [61]:
new_vertices[:, 1].max()

np.float64(7.0)

In [5]:
7/8 * np.sqrt(2) * 0.35

np.float64(0.43310290347676034)

In [6]:
b / (7/8 * np.sqrt(2))

np.float64(0.34304780412993074)

In [4]:
a = .8491 / 2
b = .849 / 2
a, b

(0.42455, 0.4245)

In [55]:
14 /separation

8.244994110718492

In [54]:
new_vertices[:, 1].max()

np.float64(14.0)

In [13]:
np.log(2)/2

np.float64(0.34657359027997264)

In [7]:
a = 0.34304780412993074

numbers = [i for i in range(1, 100)]
bases = [i for i in range(1, 20)]

best_idx = -1
best_delta = 1000

for n in numbers:
    delta = np.abs(a - np.sqrt(n))

0.34304780412993074